"""add_price_alerts_table

Revision ID: e3127ba88968
Revises: d2e6a94b3c08
Create Date: 2026-05-24 08:32:54.991503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3127ba88968'
down_revision: Union[str, Sequence[str], None] = 'd2e6a94b3c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fired_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_alert_id'), 'price_alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_price_alerts_created_at'), 'price_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_price_alerts_status'), 'price_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_price_alerts_ticker'), 'price_alerts', ['ticker'], unique=False)
    op.drop_constraint(op.f('uq_youtube_insights_video_id'), 'youtube_insights', type_='unique')
    op.drop_index(op.f('ix_youtube_insights_video_id'), table_name='youtube_insights')
    op.create_index(op.f('ix_youtube_insights_video_id'), 'youtube_insights', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_insights_video_id'), table_name='youtube_insights')
    op.create_index(op.f('ix_youtube_insights_video_id'), 'youtube_insights', ['video_id'], unique=False)
    op.create_unique_constraint(op.f('uq_youtube_insights_video_id'), 'youtube_insights', ['video_id'])
    op.drop_index(op.f('ix_price_alerts_ticker'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_status'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_created_at'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_alert_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    # ### end Alembic commands ###
